# Task 1.6

#### Importing libraries

In [1]:
# Importing libraries
import pandas as pd
import re
from thefuzz import process
import numpy as np
import spacy
from spacy import displacy
import networkx as nx
import os
import matplotlib.pyplot as plt
import scipy

## Data cleanup

In [2]:
# loading country names from the Excel file
df_countries = pd.read_csv('countries_list_20th_century_1.5.csv')

In [3]:
# cleaning country list
df_countries['country_name'] = df_countries['country_name'].str.split(',').str[0].str.strip()

In [4]:
df_countries.head()

   Unnamed: 0 country_name
0           1  Afghanistan
1           2      Albania
2           3      Algeria
3           4      Andorra
4           5       Angola

In [5]:
# converting country names to list format
standard_countries = df_countries['country_name'].tolist()

In [6]:
# open 20th century txt
with open('20th_Century_content.txt', 'r', encoding='utf-8') as file:
    text = file.read()

In [7]:
# remove extra spaces, newlines, and special characters (modify regex as needed)
text = re.sub(r"\s+", " ", text).strip()  # replace multiple spaces/newlines with a single space

In [8]:
print(text)

From Wikipedia, the free encyclopedia The 20th century changed the world in unprecedented ways. The World Wars sparked tension between countries and led to the creation of atomic bombs, the Cold War led to the Space Race and the creation of space-based rockets, and the World Wide Web was created. These advancements have played a significant role in citizens' lives and shaped the 21st century into what it is today. Historic events in the 20th century[edit] World at the beginning of the century[edit] Main article: Edwardian era The new beginning of the 20th century marked significant changes. The 1900s saw the decade herald a series of inventions, including the automobile, airplane and radio broadcasting. 1914 saw the completion of the Panama Canal. The Scramble for Africa continued in the 1900s and resulted in wars and genocide across the continent. The atrocities in the Congo Free State shocked the civilized world. From 1914 to 1918, the First World War, and its aftermath, caused major changes in the power balance of the world, destroying or transforming some of the most powerful empires. "The war to end all wars": World War I (1914–1918)[edit] Main article: World War I Arrest of a suspect in Sarajevo following the Assassination of Archduke Franz Ferdinand The First World War (or simply WWI), termed "The Great War" by contemporaries, started in July 1914 and ended in November 1918. The war was precipitated by the Assassination in Sarajevo of the Austro-Hungarian Empire's heir to the throne, Erzherzog Franz Ferdinand, by Gavrilo Princip, a member of the Young Bosnia liberation movement. After a period of diplomatic and military escalation known as the July Crisis, by the end of July 1914 two coalitions were at war: the Allies, comprised initially of the British Empire, France, and the Russian Empire; and the Central Powers, comprised initially of the German Empire and Austria-Hungary.[1][2] In 1917, Russia ended hostile actions against the Central Powers after the fall of the Tsar. The Bolsheviks negotiated the Treaty of Brest-Litovsk with Germany, although it was a huge cost to Russia. In the treaty, Bolshevik Russia ceded the Baltic states to Germany, and its province of Kars Oblast in the South Caucasus to the Ottoman Empire. It also recognized the independence of Ukraine.[3] Although Germany shifted huge forces from the eastern to the western front after signing the treaty, it was unable to stop the Allied advance, especially with the entrance of American troops in 1918.[4] The war itself was also a chance for the combatant nations to show off their military strength and technological ingenuity. The Germans introduced the machine gun,[5] U-boats[6] and deadly gases.[7] The British first used the tank.[8] Both sides had a chance to test out their new aircraft to see if they could be used in warfare. It was widely believed that the war would be short. Unfortunately, since trench warfare was the best form of defense, advances on both sides were very slow and came at a terrible cost to lives.[9] Division of Austria-Hungary after World War I When the war was finally over in 1918, the results would set the stage for the next twenty years. First and foremost, the Germans were forced to sign the Treaty of Versailles, forcing them to make exorbitant payments to repair damages caused during the War. Many Germans felt these reparations were unfair because they did not actually "lose" the war nor did they feel they caused the war (see Stab-in-the-back legend).[10] Germany was never occupied by Allied troops, yet it had to accept a liberal democratic government imposed on it by the victors after the abdication of Kaiser Wilhelm.[11] Much of the map of Europe was redrawn by the victors based upon the theory that future wars could be prevented if all ethnic groups had their own "homeland". New states like Yugoslavia and Czechoslovakia were created out of the former Austro-Hungarian Empire to accommodate the nationalist aspirations of these groups.[12] An international body called the League of Nations was formed to mediate disputes and prevent future wars, although its effectiveness was severely limited by, among other things, its reluctance and inability to act.[13] Spanish flu[edit] From 1918 to 1920, a remarkably deadly worldwide pandemic caused by the flu broke out near the end of the war and spread globally. Estimates range from anywhere between 17 to 100 million deaths,[14][15][16] which staples it as the deadliest pandemic in human history. One of the reasons for the exceptionally high carnage was that wartime censorship was underway to preserve morale in the trenches, leading to poor hygiene. Combined with already existing malnourishment and overcrowded medical facilities, this mix made it all the more deadly.[17][18] Russian Revolution and communism[edit] Main article: Russian Revolution The Russian Revolution of 1917 (ending in the overthrow of the Tsarist regime and the execution of His Imperial Majesty Nicholas II and his family) sparked a wave of communist revolutions across Europe, prompting many to believe that a socialist world revolution could be realized in the near future.[19] However, the European revolutions were defeated, Vladimir Lenin died in 1924, and within a few years, Joseph Stalin displaced Leon Trotsky as the de facto leader of the Soviet Union. The idea of worldwide revolution was no longer in the forefront, as Stalin concentrated on "socialism in one country"[20] and embarked on a bold plan of collectivization and industrialization.[21] The majority of socialists and even many communists became disillusioned with Stalin's autocratic rule, his purges and the assassination of his "enemies", as well as the news of famines he imposed on his own people.[22] Communism was strengthened as a force in Western democracies when the global economy crashed in 1929 in what became known as the Great Depression. Many people saw this as the first stage of the end of the capitalist system and were attracted to Communism as a solution to the economic crisis, especially as the Soviet Union's economic development in the 1930s was strong, unaffected by the capitalist world's crisis.[23] Between the wars[edit] Dorothea Lange's 1936 photo Migrant Mother is one of the most iconic photos associated with the Great Depression Main article: Interwar period Economic depression[edit] Main articles: Roaring Twenties and Great Depression After World War I, the global economy remained strong through most of the 1920s. The war had provided a stimulus for industry and economic activity in general. There were many warning signs foretelling the crash of 29 of the global economic system at the end of the decade, that were generally not understood by the political leadership of the time.[24] The responses to the crisis often made the situation worse, as millions of people watched their savings become next to worthless, and the idea of a steady job with a reasonable income fading away.[25] Many sought answers from alternative ideologies such as communism and fascism.[26] They believed that the capitalist economic system was collapsing and that new ideas were required to meet the crisis. The early responses to the crisis were based on the assumption that the free market would correct itself. This, however, did very little to correct the crisis or to alleviate the suffering of many ordinary people. Thus, the idea that the existing system could be reformed by government intervention in the economy, rather than by continuing the laissez-faire approach, became prominent as a solution to the crisis. Democratic governments assumed the responsibility to provide needed services in society, and to alleviate poverty, which soon gave birth to the welfare state.[27] These two politico-economic principles, the belief in government intervention and the welfare state, as opposed to the belief in the free market and private institutions, would define many political battles for the rest of the century. The rise of dictatorship[edit] Main articles: Fascism, Totalitarianism, and Dictatorship Nazi soldiers hang a poster on the window of Jewish-owned business, that says: "Germans, defend yourselves. Do not buy from Jews". Germany, 1933 Fascism first appeared in Italy with the rise to power of Benito Mussolini in 1922.[28] The ideology was supported by a large proportion of the upper classes as a strong challenge to the threat of communism.[29] When Adolf Hitler came to power in Germany in 1933, a new variant of fascism called Nazism took over Germany and ended the German experiment with democracy. The Nazi Party in Germany was dedicated to the restoration of German honor and prestige, the unification of German-speaking peoples, and the annexation of Central and Eastern Europe as vassal states, with the Slavic population to act as slave labor to serve German economic interests.[30] There was also a strong appeal to a mythical racial purity (the idea that Germans were the Herrenvolk or the "master race"), and a vicious antisemitism which promoted the idea of Jews as subhuman (Untermensch) and worthy only of extermination.[31] Many people in Western Europe and the United States greeted the rise of Hitler with relief or indifference.[32] They could see nothing wrong with a strong Germany ready to take on the communist menace to the east. Antisemitism during the Great Depression was widespread as many were content to blame the Jews for causing the economic downturn.[33] Hitler began to put his plan in motion, annexing Austria in the Anschluss, or reunification of Austria to Germany, in 1938.[34] He then negotiated the annexation of the Sudetenland, a German-speaking mountainous area of Czechoslovakia, in the Munich Conference.[35] The British were eager to avoid war and believed Hitler's assurance to protect the security of the Czech state. Hitler annexed the rest of the Czech state shortly afterwards, indicating that he had ulterior motives.[36] Fascism was not the only form of dictatorship to rise in the post-war period. Almost all of the new democracies in the nations of Eastern Europe collapsed and were replaced by authoritarian regimes.[37] Spain also became a dictatorship under the leadership of General Francisco Franco after the Spanish Civil War.[38] Totalitarian states attempted to achieve total control over their subjects as well as their total loyalty. They held the state above the individual, and were often responsible for some of the worst acts in history, such as the Holocaust Adolf Hitler perpetrated on European Jews, or the Great Purge Stalin perpetrated in the Soviet Union in the 1930s. Global war: World War II (1939–1945)[edit] Main article: World War II The war in Europe[edit] Main article: European Theater of World War II This section provides a conversational overview of World War II in Europe. See main article for a fuller discussion. The signing of the Molotov–Ribbentrop Pact in Moscow, 23 August 1939 Soon after the events in Czechoslovakia, Britain and France issued assurances of protection to Poland, which seemed to be next on Hitler's list. World War II officially began on 1 September 1939, when Hitler unleashed his Blitzkrieg, or lightning war, against Poland. Britain and France, much to Hitler's surprise, immediately declared war upon Germany, but the help they delivered to Poland was negligible.[39] Sixteen days later, Poland was attacked from the East by Soviet Union, acting in a secret alliance with Nazi Germany.[40] After only a few weeks, the Polish forces were overwhelmed, and its government fled to exile in London (see Polish government in Exile). In starting World War II, the Germans had unleashed a new type of warfare, characterized by highly mobile forces and the use of massed aircraft. The German strategy concentrated upon the devotion of the Wehrmacht, or German army, to the use of tank groups, called panzer divisions, and groups of mobile infantry, in concert with relentless attacks from the air. Encirclement was also a major part of the strategy. This change smashed any expectations that the Second World War would be fought in the trenches like the first.[41] As Hitler's forces conquered Poland, the Soviet Union, under General Secretary Joseph Stalin, was acting out guarantees of territory under a secret part of a nonaggression pact between the USSR and Germany known as the Molotov–Ribbentrop Pact. This treaty gave Stalin free rein to take the Baltic republics of Estonia, Latvia, and Lithuania, as well as Eastern Poland, all of which would remain in Soviet possession after the war.[42] Stalin also launched an attack on Finland, which he hoped to reduce to little more than a Soviet puppet state, but the Red Army met staunch Finnish resistance in what became known as the Winter War and succeeded in gaining only limited territory from the Finns.[43] This action would later cause the Finns to ally with Germany when its attack on the Soviet Union came in 1941.[44] Blitzkrieg[edit] After the defeat of Poland, a period known as the Phony War ensued during the winter of 1939–1940, which saw only limited military land operation on the Western Front.[45] This changed when Hitler occupied Denmark and Norway, beginning on 9 April 1940. Norway was strategically important because of its sea routes which supplied crucial Swedish ore to the Nazi war machine. Norway held on for a few crucial weeks, but Denmark surrendered after only six hours.[46][47] Sweden was the only Scandinavian country to successfully maintain its neutrality throughout the war, with occasional breaches of neutrality in favor of both Germany and the Western Allies.[48] On the 10 May 1940, when the Germans launched a massive attack on the Low Countries (Belgium, the Netherlands, and Luxembourg), likely to surmount the Maginot Line of defenses on the Franco-German border.[49] This witnessed the incredible fall of Eben Emael, a Belgian fort considered impregnable and guarded by 600 Belgians, to a force of only 88 German paratroopers. The worst of this was that King Leopold III of Belgium surrendered to the Germans on 28 May without warning his allies, exposing the entire flank of the Allied forces to German panzer groups.[50] With the disaster in the Low Countries, France, considered at the time to have had the finest army in the world, lasted only six weeks, with Paris being occupied on 14 June. Three days later, Marshal Philippe Pétain surrendered to the Germans.[51] The debacle in France also led to one of the war's greatest mysteries, and Hitler's first great blunder, Dunkirk, where a third of a million trapped British and French soldiers were evacuated by not only British war boats, but every craft the army could find, including fishing boats. Hitler refused to "risk" his panzers on an action at Dunkirk, listening to the advice of Air Minister Hermann Göring and allowing the Luftwaffe, or German Air Force, to handle the job.[52] The irony of this was that the escaped men would form the core of the army that was to invade the beaches of Normandy in 1944. Hitler did not occupy all of France, but about three-quarters, including all of the Atlantic coast, allowing Marshal Pétain to remain as dictator of an area known as Vichy France.[53] However, members of the escaped French Army formed around General Charles de Gaulle to create the Free French forces, which would continue to battle Hitler in the stead of an independent France.[54] At this moment, Italy, under Benito Mussolini, declared war on the Allies on 10 June, thinking that the war was almost over, but he managed only to occupy a few hundred yards of French territory.[55] Throughout the war, the Italians would be more of a burden to the Nazis than a boon, and would later cost them precious time in Greece.[56][57] German Heinkel He 111 bombers during the Battle of Britain Hitler now turned his eyes on Great Britain, which stood alone against him. He ordered his generals to draw up plans for an invasion, code named Operation Sea Lion, and ordered the Luftwaffe to launch a massive air war against the British isles, which would come to be known as the Battle of Britain. The British at first suffered steady losses, but eventually managed to turn the air war against Germany, taking down 2,698 German planes throughout the summer of 1940 to only 915 Royal Air Force (RAF) losses.[58] The key turning point came when the Germans discontinued successful attacks against British airplane factories and radar command and coordination stations and turned to civilian bombing known as terror bombing using the distinctive "bomb" sound created by the German dive-bomber, the Stuka.[59] The switch came after a small British bombing force had attacked Berlin.[60] Hitler was infuriated. However, his decision to switch the attacks' focus allowed the British to rebuild the RAF and eventually force the Germans to indefinitely postpone Sea Lion.[61] The importance of the Battle of Britain is that it marked the first of Hitler's defeats, however its overall impact was overshadowed by his later blunders in the east. Secondly, it marked the advent of radar as a major weapon in modern air war. With radar, squadrons of fighters could be quickly assembled to respond to incoming bombers attempting to bomb civilian targets. It also allowed the identification of the type and a guess at the number of incoming enemy aircraft, as well as tracking of friendly airplanes.[62] Operation Barbarossa[edit] Hitler, taken aback by his defeat over the skies of Britain, now turned his gaze eastward to the Soviet Union. Despite having signed the non-aggression pact with Stalin, Hitler despised communism and wished to destroy it in the land of its birth. He originally planned to launch the attack in early spring of 1941 to avoid the disastrous Russian winter. However, a pro-allied coup in Yugoslavia and Mussolini's almost utter defeat in his invasion of Greece from occupied Albania prompted Hitler to launch a personal campaign of revenge in Yugoslavia and to occupy Greece at the same time.[63] The Greeks would have a bitter revenge of sorts; the attack caused a delay of several crucial weeks of the invasion of the USSR, potentially hampering it.[64] Europe at the height of German control in 1942 On 22 June 1941, Hitler attacked Stalin with the largest army the world had ever seen. Over three million men and their weapons were put into service against the Soviet Union.[65] Stalin had been warned about the attack, both by other countries and by his own intelligence network, but he had refused to believe it. Therefore, the Soviet army was largely unprepared and suffered massive setbacks in the early part of the war, despite Stalin's orders to counterattack the Germans.[66] Throughout 1941, German forces, divided into 3 army groups (Army Group A, Army Group B, and Army Group C), occupied the territories of the present day Ukraine and Belarus, laid siege to Leningrad (present day Saint Petersburg), and advanced to within 15 miles of Moscow. At this critical moment, the Soviet people stalled the German Wehrmacht to a halt at the gates of Moscow. Stalin had planned to evacuate the city, and had already moved important government functions, but decided to stay and rally the city. Recently arrived troops from the east under the command of Marshal Georgy Zhukov counterattacked the Germans and drove them from Moscow.[67] Mussolini had launched an offensive in North Africa from Italian-controlled Libya into British-controlled Egypt. However, the British smashed the Italians and were on the verge of taking Libya. Hitler decided to help by sending in a few thousand troops, a Luftwaffe division, and the first-rate general Erwin Rommel.[68] Rommel managed to use his small force to repeatedly smash massively superior British forces and to recapture the port city of Tobruk and advance into Egypt. However, Hitler, embroiled in his invasion of the Soviet Union, refused to send Romm

In [9]:
# extract potential country names (using regex for capitalized words)
words = re.findall(r'\b[A-Z][a-z]+\b(?:\s[A-Z][a-z]+)*', text)

In [10]:
# fuzzy match and replace names in the text
def standardize_country(name):
    match, score = process.extractOne(name, standard_countries)
    return match if score > 90 else name # 90% is the threshold

standardized_words = {word: standardize_country(word) for word in set(words)}

In [11]:
# replace occurrences in text
for incorrect, correct in standardized_words.items():
    text = text.replace(incorrect, correct)

In [12]:
# save cleaned text
with open('Cleaned_Wiki_2.txt', 'w', encoding='utf-8') as file:
    file.write(text)

In [13]:
print("Standardization Complete. Check 'Cleaned_Wiki_2.txt'.")

Standardization Complete. Check 'Cleaned_Wiki_2.txt'.

In [14]:
# check changes made
for incorrect, correct in standardized_words.items():
    if incorrect != correct:
        print(f"Replaced: {incorrect} -> {correct}")

Replaced: Latvian -> Latvia
Replaced: Indian -> India
Replaced: Russian -> Russia
Replaced: Australian -> Australia
Replaced: The Philippines -> Philippines
Replaced: Koreas -> Korea
Replaced: Estonian -> Estonia
Replaced: The United States -> United States
Replaced: The Netherlands -> Netherlands
Replaced: German -> Germany
Replaced: Lithuanian -> Lithuania

In [15]:
# check for other non standard names
remaining_countries = [word for word in words if word not in standard_countries]
print("Potential unmatched country names:", set(remaining_countries))

Potential unmatched country names: {'Nanjing', 'Italian', 'Final Victory', 'Human', 'Related Networks', 'Wake Island', 'Global', 'Leyte Gulf', 'World Scientific', 'Henson', 'No', 'West Nile', 'Panama Canal', 'Manchukuo', 'Immediately', 'Peck', 'Cerf', 'King', 'The Decade We Almost Stopped Climate Change', 'Royal Air Force', 'Hasic', 'Gandhi', 'International Law', 'Steve', 'Tim', 'Estrada', 'Their Secret World War', 'Online Interactive', 'Rivalries', 'Little Boy', 'June', 'Centers', 'Japanese Instrument', 'Can Help Further', 'Kennedy Presidential Library', 'Roosevelt And Stalin Planned To End The Second World War', 'Even Though He Did Not Land Inside His Spacecraft', 'Cambridge', 'Masters', 'The Apollo Program', 'Began', 'National Socialist Guerrilla Movement', 'Jehovah', 'National Archives Foundation', 'From World War', 'Archduke Franz Ferdinand The First World War', 'Central Intelligence Agency', 'General Douglas Mac', 'At', 'Skylab', 'Fenton', 'Sam', 'The Pacific War', 'Latvian', 'Final', 'Jeffrey', 'League', 'Evans', 'East Asia Cultures Critique', 'The New York Times Magazine', 'Weapons', 'Warsaw', 'Cuban Missile Crisis', 'Belgrade', 'Ross', 'Elke', 'Electronic Dreams', 'Austin', 'Soviet History', 'Summer', 'Carruthers', 'Nell', 'Nazi Germany Surrenders', 'West Virginia', 'Stack', 'Alfredo', 'Up Bulletin Board Systems', 'Ghettos', 'Space Invaders', 'Africa We Must Never Forget', 'Joseph', 'Warsaw Pact', 'Main', 'The Nuremberg Code', 'Interwar', 'Events', 'Nazi', 'Signed', 'Wood', 'Wikimedia Commons', 'Designed', 'Prague', 'Fighting', 'Iron Curtain', 'Sailing Among Giant Planets', 'International Encyclopedia', 'Genocide', 'Julie', 'Einsatzgruppen', 'Norodom Sihanouk', 'Japanese', 'See', 'Community Health', 'Changed', 'Wiegrefe', 'Kyoto', 'Cabral', 'Buchenwald', 'Computer', 'Nagasaki', 'Stanford University', 'Musolf', 'Luftwaffe', 'South Manchuria Railway', 'Belgian', 'Iron Curtain Speech', 'Nazis', 'Leningrad', 'Stephanie', 'Benito Mussolini', 'Benson', 'Leon Trotsky', 'Nukes', 'The Incorporation', 'Roosevelt', 'Spanish Civil War', 'Gemini', 'Arrest', 'List', 'Regardless', 'Moon', 'Operation Overlord Day', 'Yuri Gagarin', 'Born', 'Neil', 'Finishing', 'Combined', 'First Soviet', 'Soviet Invasion', 'Inscribed', 'Indian', 'The Cold War', 'Byelorussian', 'Brosnan', 'Philippine Sea', 'Indeed', 'What', 'Forty', 'Regular', 'The Bombing', 'Gona', 'Office', 'Public Broadcasting Service', 'Kwame Nkrumah', 'European Theater', 'Michael Somare', 'The Lost Civilization', 'Lituanus', 'Iwo Jima', 'Eben Emael', 'Aug', 'Luna', 'Portuguese', 'The End', 'Western', 'Dream', 'Resistance', 'Evan', 'Dillon', 'The Formative Years', 'Holocaust Adolf Hitler', 'Timothy', 'Ben', 'September', 'Sharp', 'Rosenberg', 'Gulf', 'Selling', 'Al Jazeera', 'Sandford', 'Defense Media Network', 'Martin', 'In Rwanda', 'Fascism', 'Jomo Kenyatta', 'In France', 'Boston', 'Ian', 'Colin', 'South Korea', 'American States During', 'Why Did', 'Operation Torch', 'Normandy', 'Lacey', 'Lithuanian Quarterly Journal', 'Belgians', 'West Germany', 'Why Yuri Gagarin Remains', 'Postcolonial Borders', 'Losing Earth', 'In Wylie', 'George', 'Navy', 'Levi', 'Politics', 'Will', 'Asiatic', 'Cost', 'Yad Vashem', 'Free French', 'Tokyo Bay', 'Nuclear', 'Nazi Crimes', 'Shanks', 'Epidemiology', 'Fields', 'Why Skylab Was America', 'The Sinews', 'Leslie Alan', 'Personal Computers', 'In India', 'Who', 'Field Experiment', 'Following Chinese', 'Cold War', 'Civil Wars', 'As', 'The Boston Globe', 'Conflict That Shaped', 'Number', 'Vienna', 'The Journal', 'Free Software Revolution', 'Oklahoma City', 'Russian', 'Boris Yeltsin', 'Berlin Wall', 'Der Spiegel', 'Ezard', 'Surrender', 'William', 'Course', 'Norwich University Online', 'New Year', 'Popular Science', 'The First Reusable Spacecraft', 'Slouching Towards Utopia', 'Where Does', 'Nuclear Weapons', 'Marshal', 'German Wehrmacht', 'Stalingrad', 'South African History Online', 'August', 'Website', 'Information', 'Around', 'Tet Offensive Undermined American Faith', 'Vietnam War', 'Dictatorship', 'Jaws', 'References', 'Australian', 'The Foreign Communist Experience', 'Day', 'Manchuria', 'Know', 'Joe Mulhall', 'Escape', 'Second Congo War', 'Herder', 'Many Germans', 'Virginia', 'Mashable', 'Jason', 'With Japan', 'Stockholm International Peace Research Institute', 'Brimelow', 'The Philippines', 'Cambridge University Press', 'Katherine', 'Throughout', 'Linge', 'Potsdam', 'Photos', 'Aftermath', 'History Learning Site', 'Retrieved', 'Totalitarianism', 'Kursk Might Just Be', 'Peace', 'Victory', 'Enola Gay', 'It Was', 'Levine', 'When Lockheed', 'Cycle', 'What Caused', 'As Hitler', 'Midway', 'French', 'Estimates', 'Michaels', 'Trieste', 'How Compaq Cloned', 'Past', 'State Circuits Society Newsletter', 'Weighing', 'Major', 'Germans', 'Rex', 'Perestroika', 'Macmillan', 'Werwolf', 'Kirsch', 'Tai', 'On', 'New Guinea', 'Lee', 'Hickman', 'Tripartite Pact', 'World Wide Web', 'Korean War', 'Hollingham', 'The Brothers', 'Kim Jong', 'Serge', 'War', 'March', 'Pacific Campaign', 'Most Influential Naval Battles', 'Therefore', 'Europe During The Second World War', 'Three', 'Slavic', 'Sarajevo', 'Australian Maritime Museum', 'Allied Powers', 'Truman Doctrine', 'Year Nazi Occupation', 'The Forgotten Reason Why Japan Attacked Pearl Harbor', 'First Man', 'Crucially', 'Software Patents', 'How Was', 'Oh', 'Allied', 'Publishing Company', 'Imperial Japanese Navy', 'Hitler', 'Lincoln', 'Department', 'The Learning Network', 'Drew', 'Virtual Centre', 'The Major Alliances', 'Associated Press', 'The Leyte Gulf Example', 'Webb', 'President Richard Nixon', 'The Creative Company', 'Infectious', 'Pre', 'The Italians', 'Continent', 'The Defeat', 'Brief History', 'The Four Stages', 'The Sino', 'Why One President Gave Up His Country', 'Woollacott', 'New', 'Random House Publishing Group', 'Encirclement', 'Operation Downfall', 'Over', 'Gravel', 'Bangladesh Liberation War', 'North Africa', 'Development', 'The Great Depression', 'Innovation', 'Koreas', 'Pacific War', 'Chongqing', 'Fauci', 'King Leopold', 'Schmitter', 'Burma', 'Marshal Philippe', 'German Heinkel He', 'Wartime', 'Antonia', 'Kennedy', 'Love', 'Military Times', 'Flowers', 'Gestapo', 'Niall', 'World', 'Hirohito', 'Gutman', 'Be', 'World History', 'Auschwitz', 'Separatist Problem', 'Information Age', 'Both Germany', 'The Marco Polo Bridge Incident', 'Northern', 'Timeline', 'Andrew', 'Apple', 'Forgotten', 'Schmitt', 'Influenza Pandemic', 'New Orleans Theses', 'Social Spending Policies', 'Energy Office', 'Charlottesville', 'Five', 'German Air Force', 'Tsarist', 'Closer Look', 'Kent', 'Nuremberg Code', 'July Crisis', 'Rhodes', 'Yale University Press', 'Prange', 'Maguire', 'The Impact', 'Colossus Mark', 'Admiral Doenitz', 'May', 'Italy Tried', 'Cramming', 'Davi', 'Category', 'Chinese', 'Soon', 'East Berlin', 'Nations Fail', 'Why Hitler', 'Other', 'Here', 'An', 'Bruce', 'Michele', 'Disease', 'Maginot Line', 'Through', 'Soviets', 'Global Mortality Burden', 'Space Race', 'The Geometry', 'Erwin Rommel', 'Truman', 'East Asia', 'Graham', 'Joe', 'Goldstein', 'Jewish Victims', 'Armistice', 'Religious Overtones', 'First Post', 'Brian Lane', 'What Life Was Like For', 'Rebecca', 'Catch Fire', 'Cracking', 'North Vietnam', 'Tokyo', 'Theories', 'Krieger Publishing Company', 'North', 'Fort Eben Emael', 'While', 'Europeans', 'Alexey Leonov', 'The Avalon Project', 'Present', 'The Soviets', 'Stuka', 'The Holocaust Explained', 'Deadliest Pandemic', 'Los Alamos', 'Holocaust Teacher Resource Center', 'Domino Theory', 'Enduring Failures', 'Central European University', 'Withstanding Hitler', 'The Norway Campaign', 'Primary Documents', 'Smulkstys', 'Welcome', 'The Three Waves', 'Sino', 'Invasion', 'Capturing', 'Turning', 'Mike', 'Operation Overlord', 'Kinzer', 'Yalta', 'Becky', 'Dr', 'Invention', 'Kellaway', 'Ojo', 'Although', 'Commodore', 'The New Yorker', 'Attacks', 'Munich Conference', 'Finnish', 'Anschluss', 'Post', 'Roma', 'Blumberg', 'History Today', 'First World War', 'Although Adolf Hitler', 'Political Gain', 'It Came From Within', 'African History', 'With Boris Yeltsin', 'European', 'Mercury', 'Behind', 'Vichy France', 'Continuing', 'Everywhere', 'The Diplomat', 'Andrews', 'Ghooi', 'Friedman', 'Atlantic', 'Exile', 'Breaking', 'Eve', 'Ukrainian', 'Toronto Press', 'The Scramble', 'Sovereignty', 'Eastern Bloc Main', 'How American Journalists Reported', 'Stock Market Crash', 'Archives The', 'Nuclear Close Calls', 'Soil During World War', 'Tokyo War Crime Trial', 'Sea Lion', 'United States Army Forces', 'One', 'Lean', 'Robert', 'Plan', 'Nazi Germany', 'Edinburgh University Press', 'Alexander', 'Operation Barbarossa', 'Journalist', 'Launches Sputnik', 'Death', 'Congo Free State', 'Broken Glass', 'Wright', 'Hongkiat', 'Manhattan Project', 'The History', 'Non', 'Jung', 'Soviet Split Borne', 'Electronics', 'Tim Berners', 'Ebner', 'Sea', 'International Space Station', 'Overlook Press', 'German Empire', 'Battle', 'World War Two', 'Following World War', 'The Cuban Missile Crisis', 'Bloodiest Battles', 'Eisenhower', 'Pong', 'Assassination', 'West', 'Clifton', 'Nixon Prolonged Vietnam War', 'Pendulum', 'Oxford Research Encyclopedia', 'The System', 'Gavrilo Princip', 'This Is', 'National Geographic', 'Frontline Books', 'Democratic', 'Estonian', 'Nebraska Press', 'Darwin', 'Poole', 'The Guardian', 'Assensoh', 'Terrorism', 'Ausg', 'Pearl Harbor', 'Tom', 'Stockbauer', 'Horvitz', 'Crystal Night', 'Moore', 'Stanton', 'Sofia', 'El Alamein', 'Flanagan', 'Russian Revolution The Russian Revolution', 'Code', 'Suk', 'New Mexico', 'San Francisco', 'Fidel Castro', 'The British', 'Dot', 'The Enigma', 'Miracle', 'The Rise', 'Indian Independence Day', 'Amenta', 'First And Best Home', 'Second World War', 'Vox', 'Roberts', 'In Depth', 'South Vietnam', 'Buna', 'Tokyo War Crimes Trials', 'Bucharest', 'Test', 'Szczepaniak', 'Mukden Incident', 'Japanese Expansion', 'Dictatorship Nazi', 'Mutual', 'Despite', 'Treaty', 'Millions', 'Third World', 'Hong Kong', 'Reassessing', 'Jalopnik', 'Which', 'Factor', 'The United States', 'Preparatory Commission', 'The Radar', 'Rogers', 'Mark', 'Eventually', 'Multi', 'Phoney', 'Representatives', 'An Historical Overview', 'Berlin', 'New Perspectives', 'Flook', 'Douglas', 'Operation Passage', 'Borneo', 'File Transfer Protocol', 'London', 'Harrison', 'Hermann', 'Lessons', 'Boat Campaign That Almost Broke Britain', 'News', 'General Charles', 'Paris Is Liberated After', 'Russian Revolution', 'Fortress Europe', 'Joseph Goebbels', 'American', 'Core', 'Second Sino', 'Donald', 'The National Archives Learning Curve', 'Douglas Mac', 'Atomic Heritage Foundation', 'Collectivization', 'The National Interest', 'Sources', 'Allen', 'Happen Today', 'Touched Our Lives', 'Mahatma Gandhi', 'Emerging States', 'The Treaty', 'Harper Collins', 'Allies', 'Clinical Research', 'Egorov', 'The Discovery', 'Epidemic', 'Antisemitism', 'Burrell', 'Million Non', 'Friedrich Ebert', 'Kyoto Protocol', 'Knopf Doubleday Publishing Group', 'Uri', 'Kars Oblast', 'August Emperor Hirohito', 'The Economic History', 'Rise', 'Versailles', 'Coral Sea', 'Partition', 'On This Day', 'Semicolonweb', 'Not', 'South', 'How America Would Have Invaded Japan', 'Time', 'International Atomic Energy Agency', 'American Behavior', 'Liam', 'Penguin Books', 'Heritage Command', 'The Daily Telegraph', 'The Holocaust The Holocaust', 'The Telegraph', 'Operation Detachment', 'Alexander Perry', 'Historian', 'Kaiser Wilhelm', 'Darling', 'Lytton Report', 'From Stettin', 'Middleton', 'Balfour', 'Although Germany', 'Guam', 'Russia Invades Finland', 'The Second Battle', 'Historic', 'Thomas Dooley', 'Pakistan Frontier', 'Williams', 'Toronto', 'Britain', 'Anti', 'Arbeit Macht Frei', 'Far East', 'For', 'Venus', 'Air Minister Hermann', 'Shirer', 'Was One Year From', 'Our World', 'Giant Leap', 'Ju', 'Slave', 'There', 'American Battle Monuments Commission', 'Guadalcanal', 'Toll', 'The Netherlands', 'North Vietnamese', 'America', 'United Nations', 'Colonial Cartographies', 'Winter War', 'Brundage', 'Hope', 'Schuster', 'Perspectives', 'Modernism Modern', 'This', 'Palek', 'Free Software Foundation', 'Westminster College', 'Harold', 'Glasnost', 'Winston', 'African Political Leadership', 'Becker', 'Ban Treaty Organization', 'Charles', 'Vint', 'Milestones', 'Stab', 'Soviet', 'Colossus', 'America Online', 'Paris Peace Accords', 'Disaster', 'Hypertext', 'In French Indochina', 'Million Victims Come From', 'Erzherzog Franz Ferdinand', 'Finns', 'The Battle', 'How Appeasement Failed', 'North Africa Campaign', 'Welfare State', 'Low Countries', 'The Problem', 'The Mir Space Station Was', 'Great Purge Stalin', 'Microsoft', 'Television Show', 'North Korea', 'Running Press', 'Winston Churchill', 'Adolf Hitler', 'Nick', 'Sixth Army', 'With Hitler', 'Schmemann', 'Ravindra', 'Oddly', 'Fat Man', 'Out', 'Hutu', 'Building', 'Home Video Game Consoles', 'General Mac', 'Roaring Twenties', 'Strategic Study', 'Simon', 'Tayyab', 'Nations', 'Republics', 'Political Repression', 'Malaya', 'And Johnson Knew About It', 'Neville', 'Operation Valkyrie', 'British Burma', 'Zimmerman', 'Evolution', 'Cuban Alliance', 'Rich', 'Depth', 'Kagaayi', 'Air Force Magazine', 'Ngo', 'Dummett', 'Nuremberg Trials', 'Sudetenland', 'Fall', 'Free', 'Farley', 'Early Warnings', 'Cumings', 'Hawaii', 'National Geographic Society', 'Max', 'Guangxi', 'Blitzkrieg', 'October', 'Milne Bay', 'New Imperialism Almost', 'Dwight', 'Ferreira', 'Summary', 'Despots', 'Baltic States', 'Years Ago', 'The Great War', 'Tonkin Resolution', 'Power Pact Between Germany', 'Gordon', 'Herrenvolk', 'Mussolini', 'Why Finland', 'November', 'Amanda', 'Its', 'The New York Times', 'Jennie Rothenberg', 'Human Genome Project', 'Moscow', 'Space Museum', 'Eight Year War', 'Benj', 'Space Station Facts', 'Mir', 'Com Bubble Companies And Their Founders', 'Almost', 'Julian', 'Communications', 'Years Ago Wouldn', 'Elsewhere', 'Boris', 'Diaries Reveal How Much Wartime Germans Knew', 'Lukacs', 'Rommel', 'Psychology Press', 'From Amiens', 'Marco Polo Bridge Incident', 'Personal Computer', 'Connelly', 'Great Depression After World War', 'Serwadda', 'Voyager', 'European Jews', 'Newly Unclassified Tapes Suggest', 'Bush', 'Persia', 'Companies', 'Perry', 'Boeing', 'Endless Preliminaries', 'Apollo', 'Internet History Podcast', 'In March', 'Japanese Cabinet', 'Haaretz', 'Army Group', 'Art', 'Soviet Socialist Republics', 'Marines', 'Barbarossa', 'Crimea', 'The Campaigns', 'General Francisco Franco', 'Richard Stallman', 'Americans', 'Underdog Hero', 'From Pong', 'Revue Historique', 'Empire', 'Evidence', 'Eastern Poland', 'Brest', 'Paris', 'Fraser', 'Operation Sea Lion', 'House', 'The Motley Fool', 'Maher', 'The Warsaw Pact History', 'Julius', 'The Nuremberg Trial', 'South Caucasus', 'Freedom', 'Austro', 'The Conversation', 'Much', 'Geostrategic Consideration', 'Do', 'The German', 'Computing History', 'Resource', 'When', 'Okinawa', 'Thomas', 'End', 'Totalitarian', 'Journal', 'Most', 'Changsha', 'Some', 'Storage', 'Project', 'The Nazi', 'The Moldovans', 'Imperial War Museums', 'Paris Peace Table', 'Theoretical Readings', 'General Secretary Joseph Stalin', 'Molotov', 'Prometheus', 'The History Place', 'The Americanization', 'Libya Nuclear Disarmament', 'The Unending War', 'Schuster Paperbacks', 'Diehr', 'The Ultimate History', 'Swedish', 'The Korean War', 'Work Sets You Free', 'Reconstruction', 'Scandinavian', 'The Greeks', 'The Evacuation', 'Short History', 'Mason', 'Commercial Internet Exchange', 'Business Insider', 'This Nixon Doctrine', 'Pacific', 'The Secret History', 'Spanish', 'American Space Shuttle', 'Wannsee', 'Racist Practice', 'North Atlantic Treaty Organization', 'New York', 'Kadena Air Base', 'People', 'Amy', 'However', 'Outside', 'Soviet Prisoners', 'Disease Control', 'The Design', 'Domination', 'Saigon', 'Violence', 'These', 'Castella', 'Reports', 'The International Churchill Society', 'French Army', 'Video Games', 'The Forecast', 'The Stuka Terror', 'National Air', 'Kylie', 'The Comprehensive Nuclear', 'American Economic Association', 'World Wars', 'They', 'Centennial', 'Carrier', 'The Pentagon Papers', 'Internet The', 'The Munich Agreement', 'Compaq', 'Between', 'Naval History', 'Bolshevik Russia', 'Stalinism', 'Pacific Islands', 'What Stalin Knew', 'East Germany', 'Sputnik', 'Pacific Theater Background', 'Peng Er', 'Was', 'Marc', 'Slavs', 'Matt', 'Online', 'Industrialization', 'Bizfluent', 'Bombardment Squadron', 'The Declaration', 'Kristallnacht', 'Internet Research', 'History Extra', 'The League', 'Tech', 'What You Need To Know About The Battle', 'Foreword', 'Maria', 'Infobase Publishing', 'Columbia', 'Supreme Commander', 'Museum', 'October Revolution', 'Battelle', 'Mutual Protection', 'Zelizer', 'Reprinted', 'Mutually Assured Destruction', 'Polish', 'Many', 'Solid', 'Honors Project', 'With', 'Marks', 'Politico', 'Internet Society', 'Alex', 'Clusterfuck', 'Central Italy', 'Ribbentrop Pact', 'Holocaust Planned', 'Edwin', 'Revolution', 'After', 'Nazi Conference', 'It Can', 'Churchill', 'The Germans', 'July', 'Its Legacy', 'Like', 'Secondly', 'Dies', 'The', 'When Adolf Hitler', 'Division', 'Torchinsky', 'Pandemic Virus', 'The Independent', 'Makings', 'East', 'Marine Corps Association', 'Mariana Islands', 'Forgotten Victims', 'Dorothea Lange', 'Moon Landing', 'Computer Mouse', 'Russian Blunder', 'Company', 'Aires Oliveira', 'Bill', 'Culture', 'Computer History', 'Economic Impact', 'Slate', 'Letter', 'Lyons Press', 'Dutch East Indies', 'Nazi Persecution', 'Red Army', 'Asia', 'Keldysh', 'The Nazi Party', 'All', 'Ars Technica', 'Stalin', 'Encyclopedia', 'Susan', 'Start To The Second World War', 'Gorbachev', 'Hiroshima', 'Dobbins', 'Central', 'Center', 'Seth', 'American Army', 'The Designs', 'Defence', 'Mulhall', 'Military History', 'Knowledge', 'Saint Petersburg', 'Military Pressures Against North Vietnam', 'Tsar', 'Supreme Allied Commander', 'Several', 'Why', 'Laura', 'The Largest Naval Sea Battles', 'Rothberg', 'His Imperial Majesty Nicholas', 'Edwardian', 'Iwo Jima Mythology', 'Tobruk', 'Are', 'Craze', 'Lam', 'Casemate Publishers', 'Nichols', 'The Allied', 'Caucacus', 'Karelo', 'Members', 'Great Britain', 'How', 'Western Allies', 'Cavendish', 'Yugoslavia', 'Bulletin', 'Kamikaze', 'Pearl Harbor On', 'Cuban Missile Crisis Two', 'Britain Hitler', 'Albinko', 'Morens', 'Wrens The', 'Libya Nuclear Weapons Program', 'The World Wars', 'Paul Tibbets', 'Stanford', 'Crumbling', 'Dunya News', 'Jewish', 'Once', 'Sixteen', 'Steinweis', 'Hall', 'Computers', 'Europe', 'Hans', 'Syrett', 'Shanghai', 'The Soviet', 'Years', 'Virginia Press', 'Business', 'Dial', 'Tet Offensive', 'Anyone', 'Ticknor', 'Japanese Empire', 'And', 'Released', 'Annals', 'Early American Involvement', 'Types', 'University', 'Marshall Plan', 'British Empire', 'Richard', 'The Manhattan Project', 'Twentieth Century', 'Where Are They Now', 'Howell', 'Dunkirk', 'January', 'Opinion', 'Two', 'German Atomic Bomb Project', 'Alpes', 'Michael', 'Baltic', 'Computing', 'French Indochina', 'Positions', 'Saunders', 'Marshal Georgy Zhukov', 'The Nuclear Age', 'Nation', 'Holocaust Facts', 'Ethics', 'Bonnell', 'Western Front', 'Moldavian', 'The Great Influenza', 'My Lai', 'Vannevar Bush', 'Then', 'Brian', 'Trench Warfare', 'The Memoirs', 'The Road', 'Decolonization', 'South Carolina Press', 'Belligerents During', 'The Washington Post', 'From Racial Theory', 'Arnett', 'Siegelbaum', 'Space Shuttle', 'Hoover Institution Press', 'Initially', 'Greatest Gamble', 'In Africa', 'Third Reich', 'The Ochsner Journal', 'Infamy Speech', 'Humanity', 'This Is Africa', 'Story Behind', 'Perhaps', 'Al Gore', 'German', 'Historical Documents', 'By August', 'Nathaniel', 'South Vietnamese', 'Omaha Beach', 'Wei', 'Johnson', 'Pearlman', 'Nevertheless', 'Compuserve', 'Modern World', 'April', 'Russian Empire', 'Englund', 'Thus', 'International News', 'Henderson', 'Stuck', 'New Orleans', 'Lunokhod', 'Douglasandslavery Says', 'Allen Dulles', 'The Korean Peninsula', 'And Created An Empire', 'Stephen', 'French North A

#### 4. some errors are there but not very important

In [16]:
# load spacy English module
NER = spacy.load('en_core_web_sm')

# Load the Wiki Text

In [17]:
book = NER(text)

In [18]:
# visualize identified entities
displacy.render(book[273:20000], style = "ent", jupyter = True)

# Named Entity List per Sentence

In [19]:
df_sentences = [] # empty shell to store results

# loop through sentences, get entity list for each sentence
for sent in book.sents:
    entity_list = [ent.text for ent in sent.ents]
    df_sentences.append({"sentence": sent, "entities": entity_list})
    
df_sentences = pd.DataFrame(df_sentences)

In [20]:
df_sentences.head(10)

,sentence,entities
0,"(From, Wikipedia, ,, the, free, encyclopedia, ...","[Wikipedia, The 20th century]"
1,"(The, World, Wars, sparked, tension, between, ...","[The World Wars, the Cold War, the Space Race,..."
2,"(These, advancements, have, played, a, signifi...","[the 21st century, today]"
3,"(Historic, events, in, the, 20th, century[edit...","[20th, the 20th century]"
4,"(The, 1900s, saw, the, decade, herald, a, seri...","[The 1900s, the decade]"
5,"(1914, saw, the, completion, of, the, Panama, ...","[1914, the Panama Canal]"
6,"(The, Scramble, for, Africa, continued, in, th...","[Scramble, Africa, the 1900s]"
7,"(The, atrocities, in, the, Congo, Free, State,...",[the Congo Free State]
8,"(From, 1914, to, 1918, ,, the, First, World, W...","[1914 to 1918, the First World War]"
9,"("", The, war, to, end, all, wars, "", :, World,...","[World War I, World War I Arrest, Sarajevo, Ar..."

# Filtering Countries from Book

In [21]:
# checking all country names
print(df_countries['country_name'].unique())

['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi'
 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Costa Rica'
 'Croatia' 'Cuba' 'Cyprus' 'Czech Republic' 'Denmark' 'Djibouti'
 'Dominica' 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Fiji' 'Finland' 'France' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Bissau' 'Guyana' 'Haiti'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Ivory Coast' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Korea' 'Kuwait' 'Kyrgyzstan' 'Laos'
 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein'
 'Lithuania' 'Luxembourg' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives'
 'Mali' 'Malta' 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea'
 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania'
 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'São Tomé and Príncipe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Tajikistan' 'Tanzania'
 'Thailand' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'Turkmenistan' 'Tuvalu' 'Uganda' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Vatican City (Holy See)' 'Venezuela' 'Vietnam' 'Yemen' 'Zambia'
 'Zimbabwe' 'Abkhazia' 'Artsakh' 'Cook Islands'
 "Donetsk People's Republic" 'Kosovo' "Luhansk People's Republic" 'Niue'
 'Northern Cyprus' 'Sahrawi Arab Democratic Republic' 'Somaliland'
 'South Ossetia' 'Taiwan' 'Transnistria']

In [22]:
# filtering out entities not of interest
def filter_entity(ent_list, df_countries):
    return [ent for ent in ent_list 
            if ent in list(df_countries['country_name'])]

In [23]:
# testing
filter_entity(["Germany", "Bahamas", "2"], df_countries)

['Germany', 'Bahamas']

In [24]:
df_countries_list = list(df_countries['country_name']) 

def filter_entity(ent_list, countries_list):
    return [ent for ent in ent_list if ent in countries_list]

df_sentences['country_entities'] = df_sentences['entities'].apply(lambda x: filter_entity(x, df_countries_list))

In [25]:
df_sentences.head(150)

,sentence,entities,country_entities
0,"(From, Wikipedia, ,, the, free, encyclopedia, ...","[Wikipedia, The 20th century]",[]
1,"(The, World, Wars, sparked, tension, between, ...","[The World Wars, the Cold War, the Space Race,...",[]
2,"(These, advancements, have, played, a, signifi...","[the 21st century, today]",[]
3,"(Historic, events, in, the, 20th, century[edit...","[20th, the 20th century]",[]
4,"(The, 1900s, saw, the, decade, herald, a, seri...","[The 1900s, the decade]",[]
...,...,...,...
145,"(At, this, time, ,, Hitler, introduced, the, V...","[Hitler, V-1, V-2, first]",[]
146,"(The, V-1, was, often, intercepted, by, air, p...","[V-1, V-2]",[]
147,"(However, ,, this, advance, came, too, late, i...",[],[]
148,"(The, Germanys, were, also, on, the, verge, of...","[Germanys, Germanys, Atlantic]",[]
149,"(All, this, came, too, late, to, save, Hitler, .)",[Hitler],[]

In [26]:
unique_countries = set([country for sublist in df_sentences['country_entities'] for country in sublist])
print(unique_countries)

{'Germany', 'Italy', 'Egypt', 'Romania', 'Albania', 'Austria', 'Solomon Islands', 'Lithuania', 'Kenya', 'Netherlands', 'Korea', 'Canada', 'Finland', 'Mongolia', 'Vietnam', 'Bulgaria', 'Spain', 'Thailand', 'Latvia', 'Norway', 'Afghanistan', 'Philippines', 'Belarus', 'Seychelles', 'Denmark', 'Ghana', 'Japan', 'United States', 'Papua New Guinea', 'Hungary', 'Belgium', 'Iraq', 'Morocco', 'Algeria', 'Cuba', 'Cambodia', 'Ukraine', 'Greece', 'Rwanda', 'Sweden', 'Israel', 'Estonia', 'Poland', 'Pakistan', 'Laos', 'Lebanon', 'South Africa', 'Russia', 'Singapore', 'India', 'Iran', 'Australia', 'Libya', 'France', 'Luxembourg', 'China'}

In [27]:
# filter out sentences that don't have any character entities
df_sentences_filtered = df_sentences[df_sentences['country_entities'].map(len) > 0]

In [28]:
df_sentences_filtered.tail(10)

,sentence,entities,country_entities
1101,"("", The, forgotten, violence, that, helped, In...",[India],[India]
1106,"("", India, Independence, Day, :, everything, y...","[India Independence Day, Partition between Ind...",[Pakistan]
1115,"(^, "", Philippines, ,, 1898–1946, |, US, House...","[Philippines, 1898–1946, US House of Represent...",[Philippines]
1145,"("", Colonial, Cartographies, ,, Postcolonial, ...","[Colonial Cartographies, Postcolonial Borders,...",[Afghanistan]
1182,"(The, Moldovans, :, Romania, ,, Russia, ,, and...","[Moldovans, Romania, Russia, the Politics of C...","[Romania, Russia]"
1245,"("", Selling, ', Operation, Passage, to, Freedo...","[Thomas Dooley, the Religious Overtones of Ear...",[Vietnam]
1277,"("", Stuck, in, Endless, Preliminaries, :, Viet...","[Stuck in Endless Preliminaries, Vietnam, the ...",[Vietnam]
1548,"("", Anti, -, American, Behavior, in, the, Midd...","[Anti-American Behavior, the Middle East, a Fi...",[Lebanon]
1554,"(The, Rise, of, China, and, India, :, A, New, ...","[India, New Asian]",[India]
1555,"(Singapore, :, World, Scientific, ., doi:10.11...","[Singapore, World Scientific]",[Singapore]

# Create Relationships

In [29]:
# defining relationships 
# window size = 5 : defines how many sentences will be looked at simultaneously 
relationships = [] # create an empty list

for i in range(df_sentences_filtered.index[-1]):
    end_i = min(i+5, df_sentences_filtered.index[-1])
    country_list = sum((df_sentences_filtered.loc[i: end_i].country_entities), [])
    
    # remove duplicated characters that are next to each other
    country_unique = [country_list[i] for i in range(len(country_list)) 
                   if (i==0) or country_list[i] != country_list[i-1]]
    
    if len(country_unique) > 1:
        for idx, a in enumerate(country_unique[:-1]):
            b = country_unique[idx + 1]
            relationships.append({"source": a, "target": b})

In [30]:
df_relationship = pd.DataFrame(relationships)

In [31]:
df_relationship

      source     target
0     France    Austria
1     France    Austria
2    Austria     Russia
3     France    Austria
4    Austria     Russia
..       ...        ...
635    India  Singapore
636    India  Singapore
637    India  Singapore
638    India  Singapore
639    India  Singapore

[640 rows x 2 columns]

In [32]:
# sort cases with a->b and b->a
df_relationship = pd.DataFrame(np.sort(df_relationship.values, axis = 1), columns = df_relationship.columns)
df_relationship.head(5)

    source  target
0  Austria  France
1  Austria  France
2  Austria  Russia
3  Austria  France
4  Austria  Russia

In [33]:
# summarize interactions
df_relationship["value"] = 1
df_relationship = df_relationship.groupby(["source","target"], sort=False, as_index=False).sum()

In [34]:
df_relationship

       source       target  value
0     Austria       France      6
1     Austria       Russia      5
2     Germany        Italy     22
3     Austria      Germany      9
4     Germany        Spain      3
..        ...          ...    ...
85     Greece        Italy      3
86      Italy        Japan      6
87  Australia  Philippines      3
88    Romania       Russia      6
89      India    Singapore      5

[90 rows x 3 columns]

In [35]:
sorted_df = df_relationship.sort_values(by='value', ascending=False)
sorted_df

       source            target  value
35      China             Japan     29
2     Germany             Italy     22
5      France            Poland     21
47      China             India     17
19     France           Germany     16
..        ...               ...    ...
57      India  Papua New Guinea      3
26    Belarus             Libya      2
41  Australia   Solomon Islands      2
81   Cambodia     United States      2
56    Germany  Papua New Guinea      1

[90 rows x 3 columns]

In [36]:
df_relationship.to_csv('country_relationship.csv')